import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.185.0/build/three.module.js';

const MISSIONS=[
 {n:'Pearl Harbor',d:'7 dicembre 1941',land:false,pc:0xd8d0af,ec:0x48633c,b:'Battleship Row e Ford Island, circa 08:00. Distanze compresse per il gameplay, disposizione relativa storicamente basata.',objectives:[['Battleship Row','ship',1000],['Ford Island airfield','hangar',750],['Difese AA','aa',550]],layout:[['USS California','ship',-155,-980],['USS Maryland','ship',-80,-1110],['USS Oklahoma','ship',-35,-1110],['USS Tennessee','ship',35,-1240],['USS West Virginia','ship',80,-1240],['USS Arizona','ship',150,-1380],['USS Vestal','ship',195,-1380],['USS Nevada','ship',230,-1530],['Ford Island','hangar',-300,-1240],['Hickam Field','hangar',520,-850]],aa:[[-360,-980],[340,-1030],[-420,-1450],[410,-1510],[40,-1660]]},
 {n:'Midway',d:'4 giugno 1942',land:false,pc:0x345d80,ec:0xb7ad88,b:'Scontro aeronavale del 4 giugno. Formazioni rappresentate in scala compressa, con Kido Butai e task force USA separate.',objectives:[['Kido Butai','carrier',1150],['Scorta navale','ship',750],['CAP / difese AA','aa',500]],layout:[['Akagi','carrier',-170,-1280],['Kaga','carrier',170,-1320],['Soryu','carrier',-190,-1580],['Hiryu','carrier',190,-1620],['Scorta IJN 1','ship',-430,-1450],['Scorta IJN 2','ship',430,-1450],['USS Enterprise','carrier',-760,-2200],['USS Hornet','carrier',-480,-2300],['USS Yorktown','carrier',-1030,-2460]],aa:[[-430,-1420],[420,-1460],[-150,-1730],[180,-1760]]},
 {n:'Normandia',d:'6 giugno 1944',land:true,pc:0x536e47,ec:0x656159,b:'Settore americano del D-Day: Utah a ovest, Pointe du Hoc al centro e Omaha più a est. Geografia compressa per la missione.',objectives:[['Pointe du Hoc','aa',900],['Omaha Beach','hangar',700],['Utah Beach','armor',600]],layout:[['Utah Beach','armor',-850,-1080],['Pointe du Hoc','aa',-160,-1500],['Omaha Beach','hangar',520,-1540],['Longues-sur-Mer','aa',980,-1780],['Vierville','hangar',370,-1320],['Grandcamp','hangar',-350,-1320]],aa:[[-840,-1180],[-260,-1490],[-90,-1530],[460,-1490],[620,-1600],[980,-1760]]}
];
const $=s=>document.querySelector(s),menu=$('#menu'),game=$('#game'),end=$('#end'),missions=$('#missions'),priorities=$('#priorities');
let mi=0,order=[0,1,2],R,S,C,P,prop,clock,raf,run=false,keys={},en=[],shots=[],eshots=[],bs=[],tg=[],guns=[],fx=[],contacts=[];
let hp=100,ammo=420,bombs=6,score=0,kills=0,hits=0,fired=0,tk=0,speed=2.1,thr=.48,t=0,cam=0,lastFire=0,lastBomb=0,lastEnemy=0;
window.AeroOpsState={player:null,enemies:en,targets:tg,guns,contacts,mission:null};
function syncState(){const s=window.AeroOpsState;s.player=P;s.enemies=en;s.targets=tg;s.guns=guns;s.contacts=contacts;s.mission=MISSIONS[mi]}
function render(){missions.innerHTML='';MISSIONS.forEach((m,i)=>{const b=document.createElement('button');b.className='mission '+(i===mi?'sel':'');b.innerHTML=`<b>${m.n}</b><span>${m.d}</span>`;b.onclick=()=>{mi=i;order=[0,1,2];render()};missions.appendChild(b)});priorities.innerHTML='';order.forEach((x,r)=>{const q=document.createElement('div'),a=MISSIONS[mi].objectives[x];q.className='priority';q.innerHTML=`<span>${r+1}</span><b>${a[0]}</b><button data-u>↑</button><button data-d>↓</button>`;q.querySelector('[data-u]').onclick=()=>mv(r,-1);q.querySelector('[data-d]').onclick=()=>mv(r,1);priorities.appendChild(q)});$('#brief').textContent=MISSIONS[mi].b+' Fuoco: aerei/bersagli leggeri. Bombe: navi e bersagli pesanti.'}
function mv(i,d){const j=i+d;if(j<0||j>2)return;[order[i],order[j]]=[order[j],order[i]];render()}render();
addEventListener('keydown',e=>{keys[e.code]=1;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='KeyC'&&!e.repeat)cam=1-cam});addEventListener('keyup',e=>keys[e.code]=0);
document.querySelectorAll('[data-k]').forEach(b=>{const k=b.dataset.k;b.onpointerdown=e=>{e.preventDefault();keys[k]=1};b.onpointerup=b.onpointercancel=e=>{e.preventDefault();keys[k]=0}});
$('#start').onclick=start;$('#again').onclick=start;$('#back').onclick=()=>{stop();end.classList.add('hidden');menu.classList.remove('hidden')};
function start(){stop();menu.classList.add('hidden');end.classList.add('hidden');game.classList.remove('hidden');hp=100;ammo=420;bombs=+$('#load').value;score=kills=hits=fired=tk=0;speed=2.1;thr=.48;t=0;cam=0;en=[];shots=[];eshots=[];bs=[];tg=[];guns=[];fx=[];contacts=[];init();run=true;loop()}
function stop(){run=false;if(raf)cancelAnimationFrame(raf);raf=0;if(R){R.dispose();R.domElement.remove()}R=S=C=P=null;syncState()}
const mat=(c,r=.65,m=.06)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});
function init(){const m=MISSIONS[mi];S=new THREE.Scene();S.background=new THREE.Color(m.land?0x91aab7:0x85c5e8);S.fog=new THREE.FogExp2(S.background,.00072);C=new THREE.PerspectiveCamera(66,innerWidth/innerHeight,.1,7000);R=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});R.setPixelRatio(Math.min(devicePixelRatio,1.5));R.setSize(innerWidth,innerHeight);$('#view').appendChild(R.domElement);S.add(new THREE.HemisphereLight(0xe6f6ff,0x455345,1.7));const sun=new THREE.DirectionalLight(0xfff2d1,2);sun.position.set(-300,500,200);S.add(sun);world();P=plane(m.pc,true);P.position.set(0,+$('#alt').value,420);P.rotation.order='YXZ';P.rotation.y=Math.PI;S.add(P);historicalLayout();enemies();aa();clouds();clock=new THREE.Clock();onresize=resize;syncState();hud()}
function world(){if(!MISSIONS[mi].land){const g=new THREE.PlaneGeometry(7000,7000,45,45),p=g.attributes.position;for(let i=0;i<p.count;i++)p.setZ(i,Math.sin(p.getX(i)*.008)*1.5+Math.cos(p.getY(i)*.01));g.computeVertexNormals();const sea=new THREE.Mesh(g,mat(0x197697,.38,.08));sea.rotation.x=-Math.PI/2;S.add(sea)}else{const g=new THREE.PlaneGeometry(7000,7000,60,60),p=g.attributes.position;for(let i=0;i<p.count;i++)p.setZ(i,Math.sin(p.getX(i)*.006)*8+Math.cos(p.getY(i)*.005)*6);g.computeVertexNormals();const gr=new THREE.Mesh(g,mat(0x667d4e,1));gr.rotation.x=-Math.PI/2;S.add(gr);const beach=new THREE.Mesh(new THREE.PlaneGeometry(3300,220),mat(0xbda77b,1));beach.rotation.x=-Math.PI/2;beach.position.set(0,1,-1450);S.add(beach)}}
function plane(c,player=false){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.CylinderGeometry(7,10,58,12),mat(c,.45,.2));body.rotation.x=Math.PI/2;g.add(body);const nose=new THREE.Mesh(new THREE.ConeGeometry(7,17,12),mat(0x2c3336,.35,.3));nose.rotation.x=-Math.PI/2;nose.position.z=-37;g.add(nose);const wing=new THREE.Mesh(new THREE.BoxGeometry(75,2.2,14),mat(c,.55,.15));wing.position.z=-3;g.add(wing);const tail=new THREE.Mesh(new THREE.BoxGeometry(30,1.6,8),mat(c));tail.position.z=24;g.add(tail);const fin=new THREE.Mesh(new THREE.BoxGeometry(2,15,10),mat(c));fin.position.set(0,7,24);g.add(fin);const pr=new THREE.Group();pr.position.z=-46;pr.add(new THREE.Mesh(new THREE.BoxGeometry(2,29,1),mat(0x222a2d,.4,.3)));pr.add(new THREE.Mesh(new THREE.BoxGeometry(29,2,1),mat(0x222a2d,.4,.3)));g.add(pr);if(player)prop=pr;g.userData={kind:player?'player':'enemy',hp:player?100:36,r:26,s:1.1+Math.random()*.3};return g}
function ship(type){const g=new THREE.Group(),carrier=type==='carrier',h=new THREE.Mesh(new THREE.BoxGeometry(carrier?90:50,12,carrier?220:125),mat(0x566168,.55,.35));h.position.y=6;g.add(h);if(carrier){const d=new THREE.Mesh(new THREE.BoxGeometry(82,3,205),mat(0x34393c,.8,.15));d.position.y=14;g.add(d)}else{const s=new THREE.Mesh(new THREE.BoxGeometry(25,18,35),mat(0x687279,.65,.25));s.position.y=20;g.add(s)}g.userData.r=carrier?80:48;return g}
function ground(type){const g=new THREE.Group();if(type==='hangar'){const a=new THREE.Mesh(new THREE.BoxGeometry(72,22,48),mat(0x8a826b,.9));a.position.y=11;g.add(a)}else if(type==='armor'){const a=new THREE.Mesh(new THREE.BoxGeometry(28,8,48),mat(0x505e40,.75,.15));a.position.y=5;g.add(a);const b=new THREE.Mesh(new THREE.CylinderGeometry(9,11,7,10),mat(0x596548));b.position.y=12;g.add(b)}else{const a=new THREE.Mesh(new THREE.CylinderGeometry(13,15,5,10),mat(0x555c54,.8));a.position.y=3;g.add(a);const b=new THREE.Mesh(new THREE.CylinderGeometry(2,2,28,8),mat(0x30383b,.4,.4));b.rotation.x=Math.PI/3;b.position.set(0,15,-7);g.add(b)}g.userData.r=type==='hangar'?40:22;return g}
function historicalLayout(){const m=MISSIONS[mi];m.layout.forEach(a=>{const [name,type,x,z]=a,o=(type==='ship'||type==='carrier')?ship(type):ground(type);o.position.set(x,0,z);const baseHp=type==='carrier'?240:type==='ship'?150:type==='hangar'?90:type==='armor'?80:70;o.userData={...o.userData,name,type,kind:'contact',historical:true,dead:false,hp:baseHp,maxHp:baseHp};S.add(o);contacts.push(o)});order.forEach((objIdx,rank)=>{const wanted=m.objectives[objIdx][1];let candidate=contacts.find(o=>!tg.includes(o)&&o.userData.type===wanted);if(!candidate&&wanted==='aa')candidate=contacts.find(o=>!tg.includes(o)&&o.userData.type==='aa');if(!candidate)candidate=contacts.find(o=>!tg.includes(o));if(candidate){candidate.userData.rank=rank;candidate.userData.pts=m.objectives[objIdx][2];candidate.userData.objective=true;tg.push(candidate)}})}
function enemies(){const count=mi===1?7:5;for(let i=0;i<count;i++){const e=plane(MISSIONS[mi].ec);e.position.set((Math.random()-.5)*1000,130+Math.random()*180,-600-Math.random()*2200);e.rotation.y=Math.random()*Math.PI*2;S.add(e);en.push(e)}}
function aa(){MISSIONS[mi].aa.forEach(([x,z],i)=>{const a=ground('aa');a.scale.setScalar(.7);a.position.set(x,0,z);a.userData={...a.userData,kind:'aa',name:`AA ${i+1}`,cd:.6+Math.random()*1.4};S.add(a);guns.push(a)})}
function clouds(){const m=new THREE.MeshStandardMaterial({color:0xffffff,transparent:true,opacity:.42,depthWrite:false});for(let i=0;i<18;i++){const g=new THREE.Group();for(let j=0;j<4;j++){const s=new THREE.Mesh(new THREE.SphereGeometry(28+Math.random()*25,7,6),m);s.position.x=(j-1.5)*32;g.add(s)}g.position.set((Math.random()-.5)*2500,300+Math.random()*260,100-Math.random()*4200);S.add(g)}}
function loop(){if(!run)return;raf=requestAnimationFrame(loop);const d=Math.min(clock.getDelta(),.033);t+=d;fly(d);ai(d);bullets(d);bombUpdate(d);enemyBullets(d);flak(d);effects(d);camera(d);hud();R.render(S,C)}
function fly(d){if(keys.KeyQ)thr-=d*.24;if(keys.KeyE)thr+=d*.24;thr=THREE.MathUtils.clamp(thr,.25,.82);speed=THREE.MathUtils.lerp(speed,1.45+thr*2.25,d*1.45);const an=window.__AERO_ANALOG||{x:0,y:0,active:false};const kPitch=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0),kRoll=(keys.KeyA||keys.ArrowLeft?1:0)-(keys.KeyD||keys.ArrowRight?1:0);const pitch=an.active?-an.y:kPitch,roll=an.active?-an.x:kRoll;P.rotateX(pitch*d*.48);if(Math.abs(roll)>.015){P.rotateZ(roll*d*1.15);P.rotateY(roll*d*.24)}else{const z=((P.rotation.z+Math.PI)%(Math.PI*2)+Math.PI*2)%(Math.PI*2)-Math.PI;P.rotation.z=THREE.MathUtils.lerp(z,0,Math.min(1,d*.75))}if(Math.abs(pitch)<.015)P.rotation.x=THREE.MathUtils.lerp(P.rotation.x,0,d*.25);P.rotation.x=THREE.MathUtils.clamp(P.rotation.x,-.62,.55);P.position.addScaledVector(new THREE.Vector3(0,0,-1).applyQuaternion(P.quaternion),speed*34*d);P.position.y=THREE.MathUtils.clamp(P.position.y,24,650);prop.rotation.z+=d*(24+thr*34);if(keys.Space)fire();if(keys.KeyB)drop()}
function fire(){if(ammo<2||t-lastFire<.095)return;lastFire=t;ammo-=2;fired+=2;for(const x of[-18,18]){const s=new THREE.Mesh(new THREE.CylinderGeometry(.7,.7,22,5),new THREE.MeshBasicMaterial({color:0xfff2a0}));s.rotation.x=Math.PI/2;s.position.copy(new THREE.Vector3(x,0,-34).applyMatrix4(P.matrixWorld));s.quaternion.copy(P.quaternion);s.userData={v:new THREE.Vector3(0,0,-1).applyQuaternion(P.quaternion).multiplyScalar(650),life:1.25};S.add(s);shots.push(s)}}
function drop(){if(!bombs||t-lastBomb<.65)return;lastBomb=t;bombs--;const b=new THREE.Mesh(new THREE.CapsuleGeometry(2.2,7,4,8),mat(0x2d3530,.4,.3));b.position.copy(P.position).add(new THREE.Vector3(0,-8,5));b.rotation.x=Math.PI/2;b.userData={v:new THREE.Vector3(0,0,-1).applyQuaternion(P.quaternion).multiplyScalar(speed*28),life:12};S.add(b);bs.push(b)}
function gunDamage(a){const type=a.userData.type;if(type==='ship'||type==='carrier')return 0;if(type==='armor')return 2;if(type==='hangar')return 4;if(type==='aa')return 7;return 3}
function bombDamage(a){const type=a.userData.type;if(type==='carrier')return 100;if(type==='ship')return 100;if(type==='hangar')return 120;if(type==='armor')return 95;if(type==='aa')return 100;return 90}
function bullets(d){for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.position.addScaledVector(s.userData.v,d);s.userData.life-=d;let rem=s.userData.life<=0;if(!rem)for(let j=en.length-1;j>=0;j--){const e=en[j];if(s.position.distanceTo(e.position)<e.userData.r){e.userData.hp-=9;hits++;spark(s.position);rem=true;if(e.userData.hp<=0){boom(e.position,14);score+=300;kills++;S.remove(e);en.splice(j,1)}break}}if(!rem)for(const a of contacts)if(!a.userData.dead&&s.position.distanceTo(a.position)<a.userData.r){const dmg=gunDamage(a);if(dmg>0)a.userData.hp-=dmg;hits++;spark(s.position);rem=true;if(a.userData.objective&&a.userData.hp<=0)killTarget(a);break}if(rem){S.remove(s);shots.splice(i,1)}}}
function bombUpdate(d){for(let i=bs.length-1;i>=0;i--){const b=bs[i];b.userData.v.y-=38*d;b.position.addScaledVector(b.userData.v,d);b.rotation.x+=d*2;b.userData.life-=d;let rem=b.position.y<=2||b.userData.life<=0;for(const a of contacts)if(!a.userData.dead&&b.position.distanceTo(a.position)<a.userData.r+18){a.userData.hp-=bombDamage(a);boom(b.position,24);rem=true;if(a.userData.objective&&a.userData.hp<=0)killTarget(a);break}if(rem){boom(b.position,8);S.remove(b);bs.splice(i,1)}}}
function ai(d){for(const e of en){const to=P.position.clone().sub(e.position),dist=to.length();to.normalize();const q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,0,-1),to);e.quaternion.slerp(q,d*.15);e.position.addScaledVector(new THREE.Vector3(0,0,-1).applyQuaternion(e.quaternion),e.userData.s*36*d);if(dist<420&&t-lastEnemy>.5){lastEnemy=t;const s=new THREE.Mesh(new THREE.CylinderGeometry(.45,.45,10,5),new THREE.MeshBasicMaterial({color:0xff6655}));s.rotation.x=Math.PI/2;s.position.copy(e.position);s.userData={v:P.position.clone().sub(e.position).normalize().multiplyScalar(380),life:2};S.add(s);eshots.push(s)}}}
function enemyBullets(d){for(let i=eshots.length-1;i>=0;i--){const s=eshots[i];s.position.addScaledVector(s.userData.v,d);s.userData.life-=d;let rem=s.userData.life<=0;if(!rem&&s.position.distanceTo(P.position)<18){damage(4);spark(s.position);rem=true}if(rem){S.remove(s);eshots.splice(i,1)}}}
function flak(d){for(const a of guns){a.userData.cd-=d;if(a.userData.cd<=0&&a.position.distanceTo(P.position)<760){a.userData.cd=1.5+Math.random()*1.8;const s=new THREE.Mesh(new THREE.SphereGeometry(2.5,6,6),new THREE.MeshBasicMaterial({color:0x252525}));s.position.copy(a.position).add(new THREE.Vector3(0,16,0));s.userData={v:P.position.clone().add(new THREE.Vector3((Math.random()-.5)*100,(Math.random()-.5)*55,(Math.random()-.5)*100)).sub(s.position).normalize().multiplyScalar(210),life:1+Math.random()*1.4};S.add(s);fx.push({o:s,life:s.userData.life,flak:1})}}}
function effects(d){for(let i=fx.length-1;i>=0;i--){const f=fx[i];f.life-=d;if(f.flak)f.o.position.addScaledVector(f.o.userData.v,d);if(f.life<=0){if(f.flak){const dist=f.o.position.distanceTo(P.position);boom(f.o.position,7,0x333333);if(dist<42)damage(6+(42-dist)*.35)}S.remove(f.o);fx.splice(i,1)}}}
function spark(p){const s=new THREE.Mesh(new THREE.SphereGeometry(3.5,5,5),new THREE.MeshBasicMaterial({color:0xffdf76}));s.position.copy(p);S.add(s);fx.push({o:s,life:.2})}
function boom(p,size=12,color=0xff8b3d){const s=new THREE.Mesh(new THREE.SphereGeometry(size*.25,8,8),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8}));s.position.copy(p);S.add(s);fx.push({o:s,life:.45});s.scale.setScalar(1.6)}
function damage(x){hp=Math.max(0,hp-x);if(!hp)finish('Velivolo abbattuto')}
function killTarget(a){if(a.userData.dead)return;a.userData.dead=true;tk++;const bonus=[1.35,1.15,1][a.userData.rank]||1;score+=Math.round((a.userData.pts||500)*bonus);boom(a.position,26);a.traverse(o=>{if(o.material){o.material=o.material.clone();o.material.color.multiplyScalar(.25)}});if(tk===tg.length)setTimeout(()=>finish('Obiettivi completati'),700)}
function camera(d){let pos,look;if(!cam){pos=new THREE.Vector3(0,23,105).applyQuaternion(P.quaternion).add(P.position);look=new THREE.Vector3(0,2,-120).applyQuaternion(P.quaternion).add(P.position)}else{pos=new THREE.Vector3(0,8,-5).applyQuaternion(P.quaternion).add(P.position);look=new THREE.Vector3(0,5,-180).applyQuaternion(P.quaternion).add(P.position)}C.position.lerp(pos,1-Math.pow(.004,d));C.up.set(0,1,0);C.lookAt(look)}
function hud(){$('#hm').textContent=MISSIONS[mi].n;$('#hs').textContent=Math.round(90+thr*145);$('#ha').textContent=Math.round(P?.position.y||0);$('#hh').textContent=Math.round(hp);$('#ham').textContent=ammo;$('#hb').textContent=bombs;$('#hp').textContent=score}
function finish(reason){if(!run)return;run=false;cancelAnimationFrame(raf);score+=Math.round(hp*5);game.classList.add('hidden');end.classList.remove('hidden');$('#et').textContent=reason;$('#es').textContent=score.toLocaleString('it-IT');$('#estat').textContent=`Obiettivi ${tk}/${tg.length} · Caccia abbattuti ${kills} · Precisione ${fired?Math.round(hits/fired*100):0}% · Integrità ${Math.round(hp)}%`}
function resize(){if(!R||!C)return;C.aspect=innerWidth/innerHeight;C.updateProjectionMatrix();R.setSize(innerWidth,innerHeight)}