import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.185.0/build/three.module.js';

const canvas=document.getElementById('radarCanvas');
const ctx=canvas?.getContext('2d');
const rangeLabel=document.getElementById('radarRange');
let zoom=1,sceneEnhanced=false,markers=[];

function resize(){if(!canvas||!ctx)return;const dpr=Math.min(window.devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=Math.max(1,Math.round(r.width*dpr));canvas.height=Math.max(1,Math.round(r.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize,{passive:true});

function tri(x,y,size,fill,angle=0){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.beginPath();ctx.moveTo(0,-size);ctx.lineTo(size*.72,size);ctx.lineTo(-size*.72,size);ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.restore()}
function diamond(x,y,size,fill){ctx.save();ctx.translate(x,y);ctx.rotate(Math.PI/4);ctx.fillStyle=fill;ctx.fillRect(-size/2,-size/2,size,size);ctx.restore()}
function cross(x,y,size,stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-size,y-size);ctx.lineTo(x+size,y+size);ctx.moveTo(x+size,y-size);ctx.lineTo(x-size,y+size);ctx.stroke()}
function label(text,x,y,color='rgba(235,248,255,.92)'){ctx.font='700 8px system-ui';ctx.textAlign='left';ctx.fillStyle=color;ctx.fillText(text,x+7,y-5)}
function targetRing(x,y){ctx.save();ctx.strokeStyle='#ff4d4d';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,9,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(x-12,y);ctx.lineTo(x-7,y);ctx.moveTo(x+7,y);ctx.lineTo(x+12,y);ctx.moveTo(x,y-12);ctx.lineTo(x,y-7);ctx.moveTo(x,y+7);ctx.lineTo(x,y+12);ctx.stroke();ctx.restore()}
function isShipTarget(obj,state){return !!obj?.userData?.objective&&(obj.userData.type==='ship'||obj.userData.type==='carrier')&&(state?.targets||[]).includes(obj)}

function alive(o){return !!o&&!o.userData?.dead&&!!o.position}
function scenarioObjects(state){const all=[];if(alive(state?.player))all.push(state.player);for(const list of [state?.contacts,state?.guns,state?.enemies])for(const o of list||[])if(alive(o))all.push(o);return all}
function bounds(state){const all=scenarioObjects(state);if(!all.length)return {minX:-1200,maxX:1200,minZ:-2600,maxZ:600};let minX=Infinity,maxX=-Infinity,minZ=Infinity,maxZ=-Infinity;for(const o of all){minX=Math.min(minX,o.position.x);maxX=Math.max(maxX,o.position.x);minZ=Math.min(minZ,o.position.z);maxZ=Math.max(maxZ,o.position.z)}const px=Math.max(260,(maxX-minX)*.15),pz=Math.max(300,(maxZ-minZ)*.12);return{minX:minX-px,maxX:maxX+px,minZ:minZ-pz,maxZ:maxZ+pz}}
function mapPoint(o,b,w,h){const pad=16;const bw=Math.max(1,b.maxX-b.minX),bh=Math.max(1,b.maxZ-b.minZ);const base=Math.min((w-pad*2)/bw,(h-pad*2)/bh)*zoom;const cx=(b.minX+b.maxX)/2,cz=(b.minZ+b.maxZ)/2;return{x:w/2+(o.position.x-cx)*base,y:h/2+(o.position.z-cz)*base,scale:base}}
function plot(obj,kind,b,w,h,state){if(!alive(obj))return;const p=mapPoint(obj,b,w,h),x=p.x,y=p.y;if(x<-20||x>w+20||y<-20||y>h+20)return;if(kind==='enemy'){const f=new THREE.Vector3(0,0,-1).applyQuaternion(obj.quaternion);tri(x,y,5,'#ff6262',Math.atan2(f.x,-f.z));return}if(kind==='aa'){cross(x,y,4,'#ffb35c');return}const type=obj.userData?.type,target=isShipTarget(obj,state);if(type==='ship'||type==='carrier'){ctx.strokeStyle=target?'#ff5d5d':'#63d8ff';ctx.lineWidth=target?3:2;ctx.beginPath();ctx.rect(x-5,y-3,10,6);ctx.stroke();if(type==='carrier'){ctx.beginPath();ctx.moveTo(x-7,y);ctx.lineTo(x+7,y);ctx.stroke()}if(target){targetRing(x,y);label(`TARGET ${obj.userData?.name||''}`,x,y,'#ff8b8b')}}else{diamond(x,y,7,obj.userData?.objective?'#ffd84d':'#f6d365');if(obj.userData?.objective)label(obj.userData?.name||'',x,y)}}

function makeTextSprite(text){const c=document.createElement('canvas');c.width=512;c.height=128;const g=c.getContext('2d');g.fillStyle='rgba(110,0,0,.82)';g.roundRect(8,16,496,96,18);g.fill();g.strokeStyle='rgba(255,110,110,.95)';g.lineWidth=4;g.stroke();g.fillStyle='#fff';g.font='700 34px system-ui';g.textAlign='center';g.textBaseline='middle';g.fillText(text,256,64);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const spr=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthTest:false}));spr.scale.set(140,35,1);return spr}
function addTargetMarker(obj){if(!obj||obj.userData.__targetMarker)return;obj.userData.__targetMarker=true;const group=new THREE.Group();const ring=new THREE.Mesh(new THREE.RingGeometry(28,34,48),new THREE.MeshBasicMaterial({color:0xff3333,transparent:true,opacity:.92,side:THREE.DoubleSide,depthTest:false}));ring.rotation.x=-Math.PI/2;ring.position.y=3;group.add(ring);const beam=new THREE.Mesh(new THREE.CylinderGeometry(1.2,1.2,95,8),new THREE.MeshBasicMaterial({color:0xff4545,transparent:true,opacity:.55,depthTest:false}));beam.position.y=50;group.add(beam);const sprite=makeTextSprite(`TARGET • ${obj.userData.name||'NAVE'}`);sprite.position.y=108;group.add(sprite);obj.add(group);markers.push({group,ring,obj,phase:Math.random()*Math.PI*2})}
function enhanceScene(state){const p=state?.player;if(!p?.parent)return;const scene=p.parent;if(!sceneEnhanced){sceneEnhanced=true;scene.add(new THREE.HemisphereLight(0xbfe9ff,0x4e5840,.35));const fill=new THREE.DirectionalLight(0x9dcfff,.6);fill.position.set(350,280,-500);scene.add(fill)}for(const o of state.targets||[])if(isShipTarget(o,state))addTargetMarker(o)}
function animateMarkers(time){for(const m of markers){if(!m.obj?.parent||m.obj.userData?.dead){m.group.visible=false;continue}m.group.visible=true;const pulse=1+Math.sin(time*3+m.phase)*.08;m.ring.scale.setScalar(pulse);m.group.rotation.y+=.004}}

function draw(){requestAnimationFrame(draw);if(!canvas||!ctx)return;const game=document.getElementById('game');if(game?.classList.contains('hidden'))return;if(canvas.width===0||canvas.height===0)resize();const state=window.AeroOpsState||{},player=state.player;const r=canvas.getBoundingClientRect(),w=r.width,h=r.height,cx=w/2,cy=h/2;ctx.clearRect(0,0,w,h);const grd=ctx.createRadialGradient(cx,cy,0,cx,cy,Math.max(w,h)*.7);grd.addColorStop(0,'rgba(8,29,39,.98)');grd.addColorStop(1,'rgba(2,10,17,.98)');ctx.fillStyle=grd;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(126,218,244,.18)';ctx.lineWidth=1;for(const f of [.25,.5,.75]){ctx.beginPath();ctx.moveTo(w*f,0);ctx.lineTo(w*f,h);ctx.moveTo(0,h*f);ctx.lineTo(w,h*f);ctx.stroke()}ctx.font='700 9px system-ui';ctx.textAlign='center';ctx.fillStyle='rgba(225,246,255,.88)';ctx.fillText('N',cx,10);ctx.fillText('S',cx,h-4);ctx.fillText('W',7,cy+3);ctx.fillText('E',w-7,cy+3);
if(!player||!player.position){ctx.font='700 11px system-ui';ctx.fillStyle='#ffd88a';ctx.fillText('SINCRONIZZAZIONE…',cx,cy);return}
enhanceScene(state);animateMarkers(performance.now()/1000);const b=bounds(state);for(const o of state.contacts||[])plot(o,'contact',b,w,h,state);for(const o of state.guns||[])plot(o,'aa',b,w,h,state);for(const o of state.enemies||[])plot(o,'enemy',b,w,h,state);const pp=mapPoint(player,b,w,h),f=new THREE.Vector3(0,0,-1).applyQuaternion(player.quaternion);tri(pp.x,pp.y,7,'#8affce',Math.atan2(f.x,-f.z));ctx.strokeStyle='rgba(138,255,206,.85)';ctx.beginPath();ctx.moveTo(pp.x,pp.y);ctx.lineTo(pp.x+f.x*22,pp.y+f.z*22);ctx.stroke();ctx.font='700 8px system-ui';ctx.textAlign='right';ctx.fillStyle='rgba(220,240,248,.75)';ctx.fillText(zoom===1?'SCENARIO':'ZOOM',w-5,h-5)}

document.getElementById('radarToggle')?.addEventListener('click',()=>document.getElementById('radar')?.classList.toggle('compact'));
document.getElementById('radarZoom')?.addEventListener('click',()=>{zoom=zoom===1?1.35:1;if(rangeLabel)rangeLabel.textContent=zoom===1?'SCENARIO':'ZOOM'});
resize();draw();
await import('./loader.js?v=10');
